name: ci

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3

      - name: Terraform security scan
        uses: triat/terraform-security-scan@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: auth
        id: 'google-cloud-auth'
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          # TODO 以下2行、service_account、プロジェクト名、辺りの情報を含む。必要に応じてシークレットとして持つ。（一旦動作確認が取れたら環境を壊すので、雑に公開する。）
          workload_identity_provider: 'projects/305048719648/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'hello-sa@quantum-spring-375112.iam.gserviceaccount.com'

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: terraform init
        run: terraform init
        working-directory: ./environments/dev

      - name: terraform validate
        run: terraform validate -no-color
        working-directory: ./environments/dev

      - name: terraform plan
        run: terraform plan
        working-directory: ./environments/dev
