name: dev_cd

on:
  workflow_dispatch:

jobs:
  dev_cd:
    name: dev_cd
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: auth
        id: 'google-cloud-auth'
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: true
          # TODO 以下2行、service_account、プロジェクト名、辺りの情報を含む。必要に応じてシークレットとして持つ。（一旦動作確認が取れたら環境を壊すので、雑に公開する。）
          workload_identity_provider: 'projects/305048719648/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'hello-sa@quantum-spring-375112.iam.gserviceaccount.com'

      - name: Google Cloud login
        run: gcloud auth login --brief --cred-file="${{ steps.google-cloud-auth.outputs.credentials_file_path }}"

      - uses: actions/checkout@v3

#      - id:
