name: stg_cd

on:
  workflow_dispatch:
  push:
    branches:
    - "main"

jobs:
  stg_cd:
    name: stg_cd
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - name: auth
        id: 'google-cloud-auth'
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          workload_identity_provider: '[workload identity providerのID]'
          service_account: '[service_account]@[project_id].iam.gserviceaccount.com'

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: terraform init
        run: terraform init
        working-directory: ./environments/dev

      - name: terraform apply
        run: terraform apply -auto-approve
        working-directory: ./environments/dev
